services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: budget_management_db
    networks:
        - default
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
        - default

networks:
    default:
        driver: bridge